### PR TITLE
feature: Add '?pad' option

### PR DESCRIPTION
**Pull request by buschtoens**
Personally, I dislike the formatting inconsitency very much and would prefer `00:47:00` over `0:47:00`.

image

### CODE REVIEW

**Comment by pablopunk** [comment]
But I don't like it that way 😓 . I prefer the no padding option. Let's do this: I'll push the `?pad` option to create the behaviour you like. Also, I'll move the `?format=12` formatting into `whatTimeIsIt` cause your changes were messing with that option enabled (my bad, putting it on `render()`...)

**Comment by pablopunk** [comment]
[....vercel.app/?pad](https://time-git-fork-buschtoens-pad-all-pablopunk.vercel.app/?pad)

**Comment by buschtoens** [comment]
What about supporting fully-fledged date format strings (instead)?

e.g. via `date-fns`, `luxon`, or even the new stage 3 [`@js-temporal/polyfill`](https://www.npmjs.com/package/@js-temporal/polyfill)?
[`DateTimeFormat#formatToParts`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts) would also be highly interesting.

**Comment by pablopunk** [comment]
@buschtoens that's an interesting idea, I thought of doing a basic formatting option. But for now, I didn't find many use cases for it, so let's merge this one and see if someone is interested in that in the future 🎉

**Comment by buschtoens** [comment]
Cool! Thanks :)

**Pull request merged**
